### ISSUE TITLE
kernel error only when using c++14

### ISSUE THREAD

**Issue by hoob3rt** [jupyter-xeus/xeus-cling#322]
using c+11 or c++17 kernel is fine but c++14 gives this error
```
[E 03:47:23.350 NotebookApp] Failed to run command:
    ['/opt/anaconda1anaconda2anaconda3/bin/xcpp', '-f', '/home/hubert/.local/share/jupyter/runtime/kernel-ebb97f23-a44e-4cc4-ac77-ca7bf6daff47.json', '-std=c++14']
        PATH='/home/hubert/.conda/envs/cling/bin:/home/hubert/.zplug/bin:/home/hubert/.local/bin:/home/hubert/bin:/usr/local/bin:/home/hubert/misc/miniconda/bin:/home/hubert/misc/miniconda/condabin:/usr/local/sbin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl'
        with kwargs:
    {'stdin': -1, 'stdout': None, 'stderr': None, 'cwd': '/home/hubert/studia/mownit', 'start_new_session': True}
    
[E 03:47:23.351 NotebookApp] Uncaught exception POST /api/sessions (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='POST', uri='/api/sessions', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/home/hubert/.conda/envs/cling/lib/python3.8/site-packages/tornado/web.py", line 1703, in _execute
        result = await result
      File "/home/hubert/.conda/envs/cling/lib/python3.8/site-packages/tornado/gen.py", line 742, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/home/hubert/.conda/envs/cling/lib/python3.8/site-packages/notebook/services/sessions/handlers.py", line 69, in post
        model = yield maybe_future(
      File "/home/hubert/.conda/envs/cling/lib/python3.8/site-packages/tornado/gen.py", line 735, in run
        value = future.result()
      File "/home/hubert/.conda/envs/cling/lib/python3.8/site-packages/tornado/gen.py", line 742, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/home/hubert/.conda/envs/cling/lib/python3.8/site-packages/notebook/services/sessions/sessionmanager.py", line 88, in create_session
        kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
      File "/home/hubert/.conda/envs/cling/lib/python3.8/site-packages/tornado/gen.py", line 735, in run
        value = future.result()
      File "/home/hubert/.conda/envs/cling/lib/python3.8/site-packages/tornado/gen.py", line 742, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/home/hubert/.conda/envs/cling/lib/python3.8/site-packages/notebook/services/sessions/sessionmanager.py", line 100, in start_kernel_for_session
        kernel_id = yield maybe_future(
      File "/home/hubert/.conda/envs/cling/lib/python3.8/site-packages/tornado/gen.py", line 735, in run
        value = future.result()
      File "/home/hubert/.conda/envs/cling/lib/python3.8/site-packages/tornado/gen.py", line 209, in wrapper
        yielded = next(result)
      File "/home/hubert/.conda/envs/cling/lib/python3.8/site-packages/notebook/services/kernels/kernelmanager.py", line 168, in start_kernel
        super(MappingKernelManager, self).start_kernel(**kwargs)
      File "/home/hubert/.conda/envs/cling/lib/python3.8/site-packages/jupyter_client/multikernelmanager.py", line 158, in start_kernel
        km.start_kernel(**kwargs)
      File "/home/hubert/.conda/envs/cling/lib/python3.8/site-packages/jupyter_client/manager.py", line 305, in start_kernel
        self.kernel = self._launch_kernel(kernel_cmd, **kw)
      File "/home/hubert/.conda/envs/cling/lib/python3.8/site-packages/jupyter_client/manager.py", line 212, in _launch_kernel
        return launch_kernel(kernel_cmd, **kw)
      File "/home/hubert/.conda/envs/cling/lib/python3.8/site-packages/jupyter_client/launcher.py", line 135, in launch_kernel
        proc = Popen(cmd, **kwargs)
      File "/home/hubert/.conda/envs/cling/lib/python3.8/subprocess.py", line 854, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "/home/hubert/.conda/envs/cling/lib/python3.8/subprocess.py", line 1702, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda1anaconda2anaconda3/bin/xcpp'
```
even if i create symlink called `anaconda1anaconda2anaconda3` in `/opt/` to my conda install directory

**Comment by SylvainCorlay** [comment]
There seems to have been an issue with conda when installing your package as the relocation of the kernelspec did not occur.

I would look at th content of the kernel.json files for c++14, compared to c++11. It should *never* contain the anaconda1anaconda2 string.

**Comment by hoob3rt** [comment]
This is my c++14 kernel.json
```
{
  "display_name": "C++14",
  "argv": [
      "~/.conda/envs/cling/bin/xcpp",
      "-f",
      "{connection_file}",
      "-std=c++14"
  ],
  "language": "C++14"
}

```
and this the result of a diff
```
diff xcpp11/kernel.json xcpp14/kernel.json
```
```
2c2
<   "display_name": "C++11",
---
>   "display_name": "C++14",
7c7
<       "-std=c++11"
---
>       "-std=c++14"
9c9
<   "language": "C++11"
---
>   "language": "C++14"
```

**Comment by SylvainCorlay** [comment]
Can you do `jupyter kernelspec list`?

**Comment by hoob3rt** [comment]
Ok I managed to fixed it thanks to your help. I had some weird path to cpp14 in `jupyter kernelspec list`. Thank you
