### ISSUE TITLE
Jupyter Kernels don't show up in Jupyter after install

### ISSUE THREAD

**Issue by jordana309** [jupyter-xeus/xeus-cling#429]
I followed the install instructions, and none of the kernels showed up in Jupyter. I then copied envs/cling/share/jupyter/kernels/xcpp17/ to the /share/jupyter/kernels directory of my main install, and it showed up but can't connect.

What am I missing here?

**Comment by jordana309** [comment]
I should clarify that the same approach worked for xcpp14, just not for 17. I notice that issue #413 and #415 are possibly the same issue as this, and it looks like the solution is to get new versions of dependencies on condaforge? Does that mean I should just stick with cpp14 for now?

**Comment by AntonioDaSilva** [comment]
See #217 for this problem: it's most likely that you're running `jupyter` from the global environment that does not have the C++ kernel so you need to install `jupyter` in your new environment as shown in the issue.

**Comment by jordana309** [comment]
Thanks, Antonio! Installing jupyter in my current environment did, in fact, solve the issue. I didn't make it all way way down to #217. That fixed 11 and 14. 17 still is weird. Appreciate the help!

**Comment by erny123** [comment]
Ya this isn't working for me. 

```
conda create -n Xeuscling
conda install -c conda-forge mamba
mamba install -c conda-forge xeus-cling

jupyter kernelspec install PREFIX/share/jupyter/kernels/xcpp14 --sys-pref
ix
```


```
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/clingenv/bin/jupyter-kernelspec", line 10, in <module>
    sys.exit(KernelSpecApp.launch_instance())
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/user/miniconda3/envs/clingenv/lib/python3.13/site-packages/traitlets/config/application.py", line 1075, in launch_instance
    app.start()
    ~~~~~~~~~^^
  File "/home/evaldez/miniconda3/envs/clingenv/lib/python3.13/site-packages/jupyter_client/kernelspecapp.py", line 337, in start
    return self.subapp.start()
           ~~~~~~~~~~~~~~~~~^^
  File "/home/user/miniconda3/envs/clingenv/lib/python3.13/site-packages/jupyter_client/kernelspecapp.py", line 152, in start
    self.kernel_spec_manager.install_kernel_spec(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self.sourcedir,
        ^^^^^^^^^^^^^^^
    ...<3 lines>...
        replace=self.replace,
        ^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/userv/miniconda3/envs/clingenv/lib/python3.13/site-packages/jupyter_client/kernelspec.py", line 406, in install_kernel_spec
    shutil.copytree(source_dir, destination)
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda3/envs/clingenv/lib/python3.13/shutil.py", line 591, in copytree
    with os.scandir(src) as itr:
         ~~~~~~~~~~^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'PREFIX/share/jupyter/kernels/xcpp14'
```
